language: php

dist: xenial

services:
  - mysql

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - DB=MYSQL

before_script:
# Init PHP
  - composer self-update || true
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - export PATH=~/.config/composer/vendor/bin:$PATH
  - echo 'memory_limit = 3G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer dependencies
  - composer validate
  - composer require silverstripe/recipe-core:4.5.x-dev silverstripe/versioned:1.5.x-dev --no-update
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit
