---
Name: oauthcontroller
---
Bigfork\SilverStripeOAuth\Client\Control\Controller:
  token_handlers:
    loginhandler:
      priority: 1
      context: login
      class: Bigfork\SilverStripeOAuth\Client\Handler\LoginTokenHandler
  error_handlers:
    errorhandler:
      priority: 1
      context: login
      class: Bigfork\SilverStripeOAuth\Client\Handler\LoginErrorHandler
SilverStripe\Security\Member:
  extensions:
    - Bigfork\SilverStripeOAuth\Client\Extension\MemberExtension
---
Name: oauthauthenticator
After:
  - '#coresecurity'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        oauth: '%$Bigfork\SilverStripeOAuth\Client\Authenticator\Authenticator'
